# ignore: true
# documentation: https://docs.azimutt.app/
# slogan: Next-Gen ERD: Design, Explore, Document and Analyze your database.
# tags: erd, entity-relationship diagram, database tool, database schema, diagram
# logo: svgs/azimutt.png
# port: 4000

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
      - POSTGRES_USER=${SERVICE_USER_POSTGRES}
      - POSTGRES_DB=${POSTGRES_DB:-azimutt}
    volumes:
      - azimutt-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 20s
      retries: 10
  backend:
    container_name: azimutt-backend
    platform: linux/amd64
    image: ghcr.io/azimuttapp/azimutt:main
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SERVICE_FQDN_AZIMUTT_4000
      - SENTRY=false
      - PHX_SERVER=true
      - PHX_HOST=${SERVICE_URL_AZIMUTT}
      - PORT=${PORT:-4000}
      - DATABASE_URL=ecto://${SERVICE_USER_POSTGRES}:${SERVICE_PASSWORD_POSTGRES}@postgres/${POSTGRES_DB:-azimutt}
      - SECRET_KEY_BASE=${SERVICE_BASE64_64_AZIMUTT}
      - AUTH_PASSWORD=${AUTH_PASSWORD:-true}
      - FILE_STORAGE_ADAPTER=${FILE_STORAGE_ADAPTER:-local}
      - SKIP_ONBOARDING_FUNNEL=${SKIP_ONBOARDING_FUNNEL:-true}
      - SKIP_EMAIL_CONFIRMATION=${SKIP_EMAIL_CONFIRMATION:-true}
      - PUBLIC_SITE=${PUBLIC_SITE:-true}
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/4000' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
